apiVersion: v1
kind: Service
metadata:
  name: frontend-web
spec:
  type: NodePort
  selector:
    app: frontend-web
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web
  labels:
    app: frontend-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      labels:
        app: frontend-web
    spec:
      containers:
        - name: frontend-web
          image: rihabbennour/frontend-web:latest
          ports:
            - containerPort: 5001
